version: "3.9"

services:
  npm:
    container_name: npm
    restart: always
    image: "jc21/nginx-proxy-manager:2.11.1"
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      - DB_MYSQL_HOST=${DB_MYSQL_HOST:-npm-db}
      - DB_MYSQL_PORT=${DB_MYSQL_PORT:-3306}
      - DB_MYSQL_USER=${DB_MYSQL_USER:-npm}
      - DB_MYSQL_NAME=${DB_MYSQL_NAME:-npm-production}
      - DB_MYSQL_PASSWORD=${DB_MYSQL_PASSWORD:-npmPassword}
    volumes:
      - /home/data/npm/data:/data
      - /home/data/npm/letsencrypt:/etc/letsencrypt
    depends_on:
      - npm-db
    networks:
      - network-bridge

  npm-db:
    container_name: npm-db
    restart: always
    image: "jc21/mariadb-aria:latest"
    environment:
      - MYSQL_USER=${MYSQL_USER:-npm}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-npm-production}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-npmPassword}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-npmRootPassword}
    volumes:
      - /home/data/npm/mysql:/var/lib/mysql
    networks:
      - network-bridge

  npm-db-backup:
    container_name: npm-db-backup
    restart: always
    image: vnspc/mysql-backup:8.3
    environment:
      - TZ=${TZ:-UTC}
      - SCHEDULE=${SCHEDULE:-@weekly}
      - BACKUP_KEEP_DAYS=${BACKUP_KEEP_DAYS:-7}
      - PASSPHRASE=${PASSPHRASE:-passphrase}
      - S3_REGION=${S3_REGION:-region}
      - S3_BUCKET=${S3_BUCKET:-bucket}
      - S3_PREFIX=${S3_PREFIX:-prefix}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID:-key}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY:-secret}
      - MYSQL_HOST=${MYSQL_HOST:-mysql}
      - MYSQL_USER=${MYSQL_USER:-npm}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-npm-production}
    depends_on:
      - npm-db
    networks:
      - network-bridge

networks:
  network-bridge:
    driver: bridge
    name: network-bridge
